[package]
name = "tokiobench"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { git = "https://github.com/IgorErin/tokio.git", features = ["full"] }
criterion = "0.5.1"
itertools = "0.13.0"
tokio-metrics = { git = "https://github.com/IgorErin/tokio-metrics.git", branch = "iea/tokiodep", features = ["rt"] }
serde = "1.0.215"
serde_json = "1.0.132"

[lib]
name = "tokiobench"
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"

[[bench]]
name = "spawner"
harness = false

[[bench]]
name = "workload"
harness = false

[[bench]]
name = "remote"
harness = false

[features]
full = []
