[package]
name = "tokiobench"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { path = "tokio/tokio", features = ["full"] }
criterion = "0.5.1"
itertools = "0.13.0"
tokio-metrics = { path = "tokio-metrics", features = ["rt"] }
serde = "1.0.215"
serde_json = "1.0.132"
csv = "1.3.1"

[lib]
name = "tokiobench"
path = "src/lib.rs"

[[bin]]
name = "mspawner"
path = "src/mspawner.rs"

[[bin]]
name = "mremote"
path = "src/mremote.rs"

[[bench]]
name = "spawner"
harness = false

[[bench]]
name = "workload"
harness = false

[[bench]]
name = "remote"
harness = false

[features]
full = []
