[package]
name = "tokiobench"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { path = "tokio/tokio", features = ["full"] }
criterion = { git = "https://github.com/IgorErin/criterion.rs", branch = "iea/iter_reuse" }
itertools = "0.13.0"
tokio-metrics = { path = "tokio-metrics", features = ["rt"] }
serde = "1.0.215"
serde_json = "1.0.132"
cfg-if = "1.0.0"

[lib]
name = "tokiobench"
path = "src/lib.rs"

[[bin]]
name = "mremote"
path = "src/mremote.rs"

[[bench]]
name = "workload"
harness = false

[[bench]]
name = "remote"
harness = false

[[bench]]
name = "spawner"
harness = false

[features]
full = []
check = []
dry = []
yield = []
