name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
        profile:
          - dry
          - full
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      # TODO(unify)
      - run: cargo build --verbose
      - run: cargo build --verbose -F ${{ matrix.profile }}

      - run: cargo test --verbose

      - run: cargo bench --no-run -F check


